### ISSUE TITLE
Installing cs-web-lib gives dependency version warnings

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [dls-controls/cs-web-lib#18] opened 2023-02-14 14:43 UTC
Installing cs-web-lib gives the following dependency warnings when installing it:

```
[eyh46967@pc0103 pts_webui]$ npm install @dls-controls/cs-web-lib
npm WARN @dls-controls/cs-web-lib@0.1.16 requires a peer of @types/react@^17.0.38 but none is installed. You must install peer dependencies yourself.
npm WARN @dls-controls/cs-web-lib@0.1.16 requires a peer of @types/react-router-dom@^5.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN @dls-controls/cs-web-lib@0.1.16 requires a peer of react@^17.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN @dls-controls/cs-web-lib@0.1.16 requires a peer of react-redux@^7.1.3 but none is installed. You must install peer dependencies yourself.
```

I already have `"react": "^17.0.1"` in my `dependencies`, but the other entries are not present in any way. I believe `react-redux` should be forcibly installed if it isn't, as without it `cs-web-lib` does not work.

This issue can be recreated on the `pts_webui` repository, available on GitLab. Simply running `npm install --save-dev && npm install @dls-controls/cs-web-lib` shows the issue.

**Comment by abigailalexander** [comment] 2023-02-15 09:02
Trying to recreate this and I get a similar but slightly different message:

`[dpy45766@pc0113 pts_webui]$ npm install --save-dev && npm install @dls-controls/cs-web-lib
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
....
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: pts_webui@0.11.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0" from @apollo/client@3.3.14
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.3.14" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.3
npm ERR!   node_modules/@material-ui/core
npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.2
npm ERR!     node_modules/@material-ui/icons
npm ERR!       @material-ui/icons@"^4.11.2" from the root project
npm ERR!     peer @material-ui/core@"^4.9.10" from @material-ui/lab@4.0.0-alpha.57
npm ERR!     node_modules/@material-ui/lab
npm ERR!       @material-ui/lab@"^4.0.0-alpha.57" from the root project
npm ERR!     1 more (the root project)
npm ERR!   14 more (@material-ui/icons, @material-ui/lab, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @dls-controls/cs-web-lib@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2" from @dls-controls/cs-web-lib@0.1.16
npm ERR!   node_modules/@dls-controls/cs-web-lib
npm ERR!     @dls-controls/cs-web-lib@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

What version of npm are you running? I believe versions 3-6 of npm don't automatically install peer dependencies for you, but from 7 onwards it does (and I am running 8.19.2, so this might explain the discrepancy). There is definitely a conflict in peer dependencies though, so I'll have a look into fixing this so cs-web-lib can work in your project.

**Comment by AlexanderWells-diamond** [comment] 2023-02-15 13:49
I've upgraded my Node version to the latest (18), and I now see a very similar error to you. It looks like the dependencies I had in my `package.json` had mismatches, which older versions of NPM allowed me to have. I changed versions of various packages until I got a working set, and then tried to install cs-web-lib. This was the error I saw:
```
[eyh46967@pc0103 pts_webui]$ npm install @dls-controls/cs-web-lib
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-dom@17.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0 || ^18.0.0" from @apollo/client@3.7.7
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.7.7" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.3
npm ERR!   node_modules/@material-ui/core
npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.2
npm ERR!     node_modules/@material-ui/icons
npm ERR!       @material-ui/icons@"^4.11.2" from the root project
npm ERR!     peer @material-ui/core@"^4.9.10" from @material-ui/lab@4.0.0-alpha.57
npm ERR!     node_modules/@material-ui/lab
npm ERR!       @material-ui/lab@"^4.0.0-alpha.57" from the root project
npm ERR!     1 more (the root project)
npm ERR!   15 more (@material-ui/icons, @material-ui/lab, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-dom@17.0.1
npm ERR! node_modules/react-dom
npm ERR!   peerOptional react-dom@"^16.8.0 || ^17.0.0 || ^18.0.0" from @apollo/client@3.7.7
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.7.7" from the root project
npm ERR!   peer react-dom@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.3
npm ERR!   node_modules/@material-ui/core
npm ERR!     peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.2
npm ERR!     node_modules/@material-ui/icons
npm ERR!       @material-ui/icons@"^4.11.2" from the root project
npm ERR!     2 more (@material-ui/lab, the root project)
npm ERR!   8 more (@material-ui/icons, @material-ui/lab, ...)
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.1" from react-dom@17.0.1
npm ERR!   node_modules/react-dom
npm ERR!     peerOptional react-dom@"^16.8.0 || ^17.0.0 || ^18.0.0" from @apollo/client@3.7.7
npm ERR!     node_modules/@apollo/client
npm ERR!       @apollo/client@"^3.7.7" from the root project
npm ERR!     peer react-dom@"^16.8.0 || ^17.0.0" from @material-ui/core@4.11.3
npm ERR!     node_modules/@material-ui/core
npm ERR!       peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.2
npm ERR!       node_modules/@material-ui/icons
npm ERR!         @material-ui/icons@"^4.11.2" from the root project
npm ERR!       2 more (@material-ui/lab, the root project)
npm ERR!     8 more (@material-ui/icons, @material-ui/lab, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/eyh46967/.npm/eresolve-report.txt for a full report.
```

So from my reading, it's the version of `react` that is the entire problem. I upgraded my project to `react@17.0.2`, to match cs-web-lib, and that allows me to successfully install cs-web-lib.

This issue then is only valid if it's allowable to use different versions of `react` in a project compared to this library.

**Comment by aawdls** [comment] 2023-02-15 14:00
Thanks both.

@AlexanderWells-diamond I think we can probably state support for only one major React version and that it should be a normal dependency rather than a "peer" dependency (of which I only have a limited understanding, but I think is not appropriate here). Though the exact version conflict is not clear to me from the error message above. What version of react did you have previously?

@abigailalexander Please continue to sanity-check our dependency set. Then assuming no major problems found close this issue.

**Comment by AlexanderWells-diamond** [comment] 2023-02-15 14:01
I was running `react@17.0.1`, I upgraded to `react@17.0.2` and the problem went away.

I've just started a server and seen some runtime warnings emitted by `cs-web-lib`:
```
./node_modules/@dls-controls/cs-web-lib/dist/esm/index.js
Module not found: Can't resolve 'bufferutil' in '/home/eyh46967/dev/pts_webui/node_modules/@dls-controls/cs-web-lib/dist/esm'

./node_modules/@dls-controls/cs-web-lib/dist/esm/index.js
Module not found: Can't resolve 'utf-8-validate' in '/home/eyh46967/dev/pts_webui/node_modules/@dls-controls/cs-web-lib/dist/esm'
```
These sound like there are some missing dependencies somewhere?

**Comment by aawdls** [comment] 2023-02-17 14:35
Agreed approach with @abigailalexander 

- Update the peer-dependency pin of react in cs-web-lib to ^17.0.0, we dont think 17.0.2 is reequired
- Reproduce the last warnings (we don't see them in machine-status for example)
- Look at adding the webpack config that looks like it will help with the last message

**Comment by abigailalexander** [comment] 2023-03-01 15:44
Regarding the warning about missing dependencies, it seems like the ws package https://github.com/websockets/ws has optional peer dependencies for `bufferutil` and `utf-8-validate` and this is the source of the warning. These packages - if included - are apparently addons that improve the performance of certain operations. They aren't necessary for functionality, but will now be included in cs-web-lib.

I've done this and also updated the pinned peer dependency of React to ^17.0.0 in PR #21 as 17.0.2 isn't required. It seems that version was pinned as it was the first version of React 17 to be included in cs-web-lib.

**Closed** 2023-03-02 08:08 UTC
